#!/bin/bash

#PBS -N sortbam
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=04:00:00
#PBS -l ncpus=12
#PBS -l mem=48GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

set -xue


/g/data/xf3/zz3507/app/seqkit sort -l -r /g/data/xf3/zz3507/Output/AfterHiCProcessing/H1V2H2V6ReferenceFinal20240711/H2reference/H2V6/H2V6.First22.FINAL.fa \
-o /g/data/xf3/zz3507/Output/AfterHiCProcessing/H1V2H2V6ReferenceFinal20240711/H2reference/H2V6/H2V6.First22.FINAL.sorted.fa