#!/bin/bash
#PBS -q normal
#PBS -l mem=64GB
#PBS -l walltime=48:00:00
#PBS -l ncpus=16
#PBS -l jobfs=400GB
#PBS -l wd
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2+gdata/fa63
#PBS -P fa63

source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/miniconda/envs/fastp


output_dir="/g/data/xf3/zz3507/RawData/ctrapeziformis_RNA/trimmed_chiloglottis"

cd /g/data/xf3/zz3507/RawData/ctrapeziformis_RNA/chiloglottis
## Trimming reads
# Loop over forward read files (*_1.fastq.gz)
i="/g/data/xf3/zz3507/RawData/ctrapeziformis_RNA/chiloglottis/112c_S1.fastq.gz"

    # Print message indicating the file being trimmed

    # Run fastp for trimming. Adjust the path to fastp if necessary
    fastp -w 16 -5 -3 -r -W 10 -M 20 -l 100 \
        -i "${i}" \
        -h "${output_dir}/${variable}.html" \
        -o "${output_dir}/112c_S1.fastq.gz" 
