#!/bin/bash
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=24:00:00
#PBS -l ncpus=8
#PBS -l mem=300GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


set -xue
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/miniconda/envs/jellyfish


cd /g/data/xf3/zz3507/Output/AfterHiCProcessing/jellyfish/ONT

#gunzip -c /g/data/xf3/zz3507/Output/chopper_output/Q720K/MergedONTQ720K/mergedONTQ720K.fq.gz > /g/data/xf3/zz3507/Output/chopper_output/Q720K/MergedONTQ720K/mergedONTQ720K.fq

jellyfish count -C -m 21 -s 1000000000 -t 8 /g/data/xf3/zz3507/Output/chopper_output/Q720K/MergedONTQ720K/mergedONTQ720K.fq -o kmer_counts.jf
jellyfish histo kmer_counts.jf > kmer_k21.his