#!/bin/bash
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=24:00:00
#PBS -l ncpus=1
#PBS -l mem=48GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


set -xue
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/miniconda/envs/jellyfish

cd /g/data/xf3/zz3507/Output/AfterHiCProcessing/jellyfish/hifi

smudgeplot.py plot kmer_pairs_coverages.tsv -o my_genome