#!/bin/bash
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=12
#PBS -l mem=96GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

set -xue
# Load necessary modules and activate conda environment
# Define paths
REF="/g/data/xf3/zz3507/Output/AfterHiCProcessing/H1reference/yahsMarkedPCRRNocorrection/yahsMarkedPCRNocorrection50KH1First30Scaffolds.fa"
PB_FOFN="/g/data/xf3/zz3507/script/purge_dups/pacbio_files_list.txt"
PURGE_DUPS_BIN="/g/data/xf3/zz3507/envs/purge_dups/purge_dups/bin"
CONFIG="config.Ct.json"
OUT_DIR="/g/data/xf3/zz3507/Output/AfterHiCProcessing/PurgeDups/hap1"

cd $OUT_DIR

source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate purge_dups

# Generate configuration file
/g/data/xf3/zz3507/envs/purge_dups/purge_dups/scripts/pd_config.py -n $CONFIG $REF $PB_FOFN

# Modify configuration file if needed (optional)
# nano $CONFIG
# Run Purge Dups pipeline
python3 /g/data/xf3/zz3507/envs/purge_dups/purge_dups/scripts/run_purge_dups.py -p bash $CONFIG $PURGE_DUPS_BIN Ct