#!/bin/bash

#PBS -P xf3
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -l ncpus=40
#PBS -l mem=160GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2
#PBS -l wd
#PBS -m abe

/g/data/xf3/zz3507/envs/minimap2-2.28_x64-linux/minimap2 -t 40 -ax asm5 --eqx \
/g/data/xf3/zz3507/script/syri/yahs500KNoCorrectionQ20RemovedPCRFirst30contigH2.fa \
/g/data/xf3/zz3507/script/syri/yahsMarkedPCRNocorrection50KH1.fa \
> SyriOut.sam
