#!/bin/bash
#PBS -N AfterYahsJuicertoolsH2
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=24:00:00
#PBS -l ncpus=32
#PBS -l mem=128GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


cd /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahsNoCorrectionQ20

cut -f 1-2 ./yahs.out_scaffolds_final.fa.fai >./yahs.out_scaffolds_final.fa.chrom.sizes

set -xue
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/miniconda/envs/samtools

samtools faidx ./yahs.out_scaffolds_final.fa

(java -jar -Xmx128G /g/data/xf3/zz3507/envs/JuicerTools1.22.01.jar pre \
./alignments_sorted.txt \
out.hic.part \
./yahs.out_scaffolds_final.fa.chrom.sizes) \
&& (mv out.hic.part out.hic)

