#!/bin/bash
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=24:00:00
#PBS -l ncpus=64
#PBS -l mem=128GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2
#PBS -m abe
#PBS -M Zirui.Zhang@anu.edu.au 

/g/data/xf3/zz3507/app/iqtree-2.3.5-Linux-intel/bin/iqtree2 \
-S /g/data/xf3/zz3507/database/GeneFamilyExpentionContractionDataset/OrthoFinder/Results_Jul23/IQTREE_ortho_MSA \
-cmax 15 -msub nuclear -m MFP+Merge -alrt 1000 -nt 64 --prefix loci_cmax15_msubnucl_MFPmerge_alrt_IQTREE_ortho_MSA ##Gene tree