#!/bin/bash
#PBS -N AfterYahsJuicertoolsH2
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=8
#PBS -l mem=32GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

(java -jar -Xmx32G /g/data/xf3/zz3507/envs/JuicerTools1.22.01.jar pre /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahs/alignments_sorted.txt /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/ContactMatrixH2/out.ContactMatrixH2.part /g/data/xf3/zz3507/script/HiC-Pro/contignumberBigger50KH2) && (mv out.hic.part out.hic)