#!/bin/bash
#PBS -N bowtie2H2
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=4
#PBS -l mem=32GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate bowtie2


bowtie2-build /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/MergedHap1Hap2/mergedH1H2Q720KOntHifiHiCBigger50K.ctg.fasta /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/MergedHap1Hap2/MergedHap1Hap2.hic_ctg