#!/bin/bash
#PBS -P fa63
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2
#PBS -m abe
#PBS -M Zirui.Zhang@anu.edu.au 

/g/data/xf3/zz3507/app/cafe/CAFE5/bin/cafe5 -c 48 -i /g/data/xf3/zz3507/database/GeneFamilyExpentionContractionDatasetH1/OrthoFinder/Results_Sep23/Orthogroups/Orthogroups.GeneCount_h1_Sep24_100.tsv \
-t /g/data/xf3/zz3507/database/GeneFamilyExpentionContractionDatasetH1/OrthoFinder/Results_Sep23/Species_Tree/SpeciesTree_rooted.txt -o /g/data/xf3/zz3507/database/GeneFamilyExpentionContractionDatasetH1/OrthoFinder/Results_Sep23