#!/bin/bash
#PBS -N bowtie2H2500K
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=24:00:00
#PBS -l ncpus=4
#PBS -l mem=16GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate bowtie2


bowtie2-build /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC500K/assemblyQ720KOntHifiHiC500K.hic.hap2.fasta  /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC500K/bowtie2_index/assemblyQ720KOntHifiHiCBigger500Kcontig.hic.hap2_ctg