#!/bin/bash

#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=32
#PBS -l mem=128GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2+gdata/if89
#PBS -l wd

set -xue


source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate biopython
export PATH=$PATH:/g/data/xf3/zz3507/app/last-1550/bin

cd /g/data/xf3/zz3507/Output/AfterHiCProcessing/syteny_plot/H1vsH2.V3

python -m jcvi.compara.catalog ortholog H1 H2 --no_strip_names --min_size 5 --dist 35

python -m jcvi.compara.synteny screen --minspan=30 --simple H1.H2.lifted.anchors H1.H2.lifted.anchors.simple

python -m jcvi.graphics.karyotype seqids layout
