#!/bin/bash
#PBS -N yahsh1
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=24
#PBS -l mem=96GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


set -xue
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/miniconda/envs/samtools

cd /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC500K/

samtools faidx /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC500K/assemblyQ720KOntHifiHiC500K.hic.hap2.fasta
cut -f 1-2 ./assemblyQ720KOntHifiHiC500K.hic.hap2.fasta.fai >./assemblyQ720KOntHifiHiC500K.hic.hap2.fasta.chrom.sizes