#!/bin/bash
#PBS -N Juicerh2
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=36:00:00
#PBS -l ncpus=72
#PBS -l mem=288GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

set -xue

module load java/jdk-8.40
module load python2/2.7.17
module load parallel/20191022
module load bwa/0.7.17
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate juicer

# change working directiory
cd /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/Juicer

/g/data/xf3/zz3507/envs/JuicerAddChiloglottisRestrictionEnzyme/juicer/CPU/juicer.sh -g draft -s Chiloglottis -z /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap2_ctg.fasta -y /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/Juicer/draft_Chiloglottis_h2.txt -p assembly -t 72 -D /g/data/xf3/zz3507/envs/JuicerAddChiloglottisRestrictionEnzyme/juicer