#!/bin/bash

#PBS -N Sam2BamSort
#PBS -l ncpus=16
#PBS -l mem=128GB
#PBS -l jobfs=100GB
#PBS -q normal
#PBS -P xf3
#PBS -l walltime=48:00:00
#PBS -l storage=gdata/xf3+scratch/xf3
#PBS -l wd
#PBS -m abe

set -xue
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/miniconda/envs/samtools


# Set the input SAM files
SAM_FILE1="/g/data/xf3/zz3507/Output/AfterHiCProcessing/minimap/H1ONTaln.sam"

# Set the output BAM file names
BAM_FILE1="/g/data/xf3/zz3507/Output/AfterHiCProcessing/minimap/H1ONTialn.bam"

# Convert SAM to BAM using samtools
samtools view -b -@16 $SAM_FILE1 -o $BAM_FILE1

# Sort the BAM files
samtools sort -@16 $BAM_FILE1 -o ${BAM_FILE1%.bam}_sorted.bam

# Index the sorted BAM files
samtools index -@16 ${BAM_FILE1%.bam}_sorted.bam

