#!/bin/bash
#PBS -N HiCProH2
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=15:00:00
#PBS -l ncpus=72
#PBS -l mem=288GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xf3/zz3507/envs/HiC-Pro/


/g/data/xf3/zz3507/envs/HiC-Pro/HiC-Pro_3.1.0/bin/HiC-Pro -i /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/fastq/ -o /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/HiCPro -c /g/data/xf3/zz3507/script/HiC-Pro/config-hicpro.txt