#!/bin/bash

#PBS -P fa63
#PBS -q normalsr
#PBS -l walltime=48:00:00
#PBS -l ncpus=80
#PBS -l mem=320GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2
#PBS -l wd
#PBS -m abe

/g/data/xf3/zz3507/envs/minimap2-2.28_x64-linux/minimap2 -t 80 -ax map-ont --secondary=no /g/data/xf3/zz3507/Output/AfterHiCProcessing/AfterJuicerEditing/0604H1V1.1.500K/merged_H1V1.1H2V6.500K.fasta /g/data/xf3/zz3507/Output/AfterHiCProcessing/subsampleONT/ONTQ720K1.4M.fq > /g/data/xf3/zz3507/Output/AfterHiCProcessing/minimapHIFIONTreadsBackToScaffolds/H1H2ONT/H1V1.1H2V6.500K.ONTONTQ720K1.4Maln.sam
