#!/bin/bash
#PBS -N JBAT
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=24:00:00
#PBS -l ncpus=8
#PBS -l mem=64GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

cd /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahsNoCorrectionJBAT


/g/data/xf3/zz3507/envs/yahs/yahs/juicer pre -a -o out_JBAT /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahsNoCorrection/yahs.out.bin \
/g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahsNoCorrection/yahs.out_scaffolds_final.agp \
/g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/JuicerYan/references/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap2_ctg.fasta.fai \
>out_JBAT.log 2>&1



(java -jar -Xmx128G /g/data/xf3/zz3507/envs/JuicerTools1.22.01.jar pre \
out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log  | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)