#!/bin/bash

#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=24
#PBS -l mem=96GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2+gdata/if89
#PBS -l wd


source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate /g/data/if89/apps/plotsr


python3 /g/data/if89/apps/syri -c /g/data/xf3/zz3507/script/minimap2/mapTwoHiCResults/SyriOut.sam -r /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap1/yahsMarkedPCRRNocorrection/yahsMarkedPCRNocorrection50KH1.fa -q /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahs500KNoCorrectionQ20RemovedPCR/yahs500KNoCorrectionQ20RemovedPCR.fa -k -F S
python3 plotsr syri.out /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap1/yahsMarkedPCRRNocorrection/yahsMarkedPCRNocorrection50KH1.fa /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/yahs500KNoCorrectionQ20RemovedPCR/yahs500KNoCorrectionQ20RemovedPCR.fa -H 8 -W 5