#!/bin/bash

#PBS -P fa63
#PBS -q normalsr
#PBS -l walltime=48:00:00
#PBS -l ncpus=80
#PBS -l mem=320GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2
#PBS -l wd
#PBS -m abe

/g/data/xf3/zz3507/envs/minimap2-2.28_x64-linux/minimap2 -t 80 -ax map-ont /g/data/xf3/zz3507/Output/AfterHiCProcessing/H1reference/yahsMarkedPCRRNocorrection/yahsMarkedPCRNocorrection50KH1.fa /g/data/xf3/zz3507/Output/AfterHiCProcessing/subsampleONT/ONTQ720K1.4M.fq > /g/data/xf3/zz3507/Output/AfterHiCProcessing/minimapHIFIONTreadsBackToScaffolds/H1V1ONT/H1V1ONTONTQ720K1.4Maln.sam
