#!/bin/bash
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=4
#PBS -l mem=16GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


output_dir="/g/data/xf3/zz3507/Output/AfterHiCProcessing/H1V3H2V7ReferenceAUG17FFF/H1/HiC"
mkdir $output_dir
cd $output_dir



set -xue

/g/data/xf3/zz3507/envs/yahs/juicer post -o out_JBATH1 \
/g/data/xf3/zz3507/Output/AfterHiCProcessing/H1V3H2V7ReferenceAUG17FFF/H1/17AUGH1V3HiCFFF.review.assembly \
/g/data/xf3/zz3507/Output/AfterHiCProcessing/H1V2H2V6ReferenceFinal20240711/H1reference/0708H1V2HiCFinal/out_JBAT.liftover.agp \
/g/data/xf3/zz3507/Output/AfterHiCProcessing/H1V3H2V7ReferenceAUG17FFF/H1/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap1_ctg.fasta