#!/bin/bash

#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=16
#PBS -l mem=64GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2+gdata/if89
#PBS -l wd

set -xue


source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate biopython
export PATH=$PATH:/g/data/xf3/zz3507/app/last-1550/bin

cd /g/data/xf3/zz3507/Output/AfterHiCProcessing/syteny_plot

python -m jcvi.compara.catalog ortholog H1V1 H2V6 --no_strip_names