#!/bin/bash
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=4
#PBS -l mem=16GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


output_dir="/g/data/xf3/zz3507/Output/AfterHiCProcessing//AfterJuicerEditing/0603V6/h2/"
mkdir $output_dir
cd $output_dir

set -xue

/g/data/xf3/zz3507/envs/yahs/yahs/juicer post -o out_JBATH2 /g/data/xf3/zz3507/Output/AfterHiCProcessing/AfterJuicerEditing/0603V6/yahsH2NoCorrectionNoQ50KnewV6.review.review.assembly /g/data/xf3/zz3507/Output/AfterHiCProcessing/H2reference/yahsNoCorrectionFinal/yahsNoCorrectionJBAT/out_JBAT.liftover.agp /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/JuicerYan/references/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap2_ctg.fasta