#!/bin/bash
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=4
#PBS -l mem=16GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2


output_dir="/g/data/xf3/zz3507/Output/AfterHiCProcessing/AfterJuicerEditing/0708H1V1Final"

set -xue
# Create output directory
mkdir -p "$output_dir"
cd "$output_dir" 


set -xue

/g/data/xf3/zz3507/envs/yahs/juicer post -o out_JBATH1 \
/g/data/xf3/zz3507/Output/AfterHiCProcessing/AfterJuicerEditing/0708H1V2Final/H1V28JulFinal.review.assembly \
/g/data/xf3/zz3507/Output/AfterHiCProcessing/H1reference/yahsMarkedPCRRNocorrection/out_JBAT.liftover.agp \
/g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap1/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap1_ctg.fasta