#!/bin/bash
#PBS -P xf3
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

set -xue

source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate jcvi

python -m jcvi.compara.catalog ortholog /g/data/xf3/zz3507/database/OtherOrchidGenome/PlatantheraZijinensis/data/GCA_039513925.1/GCA_039513925.1_PZIJ_v1.0_genomic.fna /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC500K/yahs500KQ20NoCorrection/yahs.out_scaffolds_final.fa --no_strip_names