#!/bin/bash
#PBS -N Juicerh2Yan
#PBS -P xf3
#PBS -q normalsr
#PBS -l walltime=15:00:00
#PBS -l ncpus=104
#PBS -l mem=416GB
#PBS -l jobfs=400GB
#PBS -l storage=scratch/xf3+gdata/xf3+gdata/xe2

set -xue

module load java/jdk-8.40
module load python2/2.7.17
module load parallel/20191022
module load bwa/0.7.17
source /g/data/xf3/miniconda/etc/profile.d/conda.sh
conda activate juicer

# change working directiory
cd /g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/JuicerYan

export wdir=/g/data/xf3/zz3507/Output/assemblyQ720KOntHifiHiC/assemblyQ720KOntHifiHiCBiggerThan50KContig/hap2/JuicerYan

scripts/juicer.sh -S early -s Chiloglottis -D ${wdir} -g ${wdir}/references/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap2_ctg.fasta \
-z ${wdir}/references/assemblyQ720KOntHifiHiCBigger50Kcontig.hic.hap2_ctg.fasta -y ${wdir}/restriction_sites/draft_Chiloglottis_h2.txt -p $wdir/contignumberBigger50KH2 -t 104